version: 2

jobs:
  test:
    working_directory: ~/go/src/github.com/lightstep/opentelemetry-prometheus-sidecar
    docker:
      - image: circleci/golang:1.14
    steps:
      - checkout
      - run:
          name: "install prometheus"
          command: |
            mkdir $HOME/prom
            cd $HOME/prom
            git clone git@github.com:prometheus/prometheus.git
            cd $HOME/prom/prometheus
            git checkout v`cat $HOME/go/src/github.com/lightstep/opentelemetry-prometheus-sidecar/PROM_VERSION`
            go install ./cmd/prometheus
      - run: go test ./...
      - run: go test -race ./...
      - run: make

workflows:
  version: 2
  test:
    jobs:
      - test
