name: Build

on:
  push:
    branches: [ 'bobclarke/*' ]
  #pull_request:
  #  branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15
        
    - name: Install Prometheus
      run: |
        echo ">>> Installing prometheus"
        export PROM_VERSION=`cat $GITHUB_WORKSPACE/PROM_VERSION`
        mkdir $HOME/prom
        cd $HOME/prom/
        wget https://github.com/prometheus/prometheus/releases/download/v${PROM_VERSION}/prometheus-${PROM_VERSION}.linux-amd64.tar.gz
        tar -xvzf prometheus-${PROM_VERSION}.linux-amd64.tar.gz
        mkdir -p $GITHUB_WORKSPACE/bin
        cp prometheus-${PROM_VERSION}.linux-amd64/prom* $GITHUB_WORKSPACE/bin
        echo "$GITHUB_WORKSPACE/bin" >> $GITHUB_PATH
        echo ">>> Completed installation of Prometheus"

    - name: Build
      run: |
        echo ">>> Starting build"
        make
        echo ">>> Starting build"

    - name: Test
      run: go test ./...

    - name: Test w/ race
      run: go test -race ./...
