name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15
        
    - name: Install Prometheus
      run: |
        mkdir $HOME/prom
        cd $HOME/prom
        git clone https://github.com/prometheus/prometheus.git
        cd $HOME/prom/prometheus
        git checkout v`cat $GITHUB_WORKSPACE/PROM_VERSION`
        go install ./cmd/prometheus

    - name: Build
      run: make

    - name: Test
      run: go test ./...

    - name: Test w/ race
      run: go test -race ./...
