name: Deploy
on:
  push:
    tags:
      - 'd*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Codefresh pipeline runner
      uses: codefresh-io/codefresh-pipeline-runner@v5
      env:
        PIPELINE_NAME: 'otel-sidecar-cicd/deploy-to-staging'
        CF_API_KEY: ${{ secrets.CODEFRESH_API_TOKEN }}
      id: run-pipeline