name: Deploy
on:
  push:
    tags:
      - 'd*'

env:
  GITHUB_SHA: ${{ github.sha }}
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: setup
      shell: bash
      run: export SHORT_GITHUB_SHA=sha-${GITHUB_SHA::8}

    - name: Codefresh pipeline runner
      uses: codefresh-io/codefresh-pipeline-runner@v7
      env:
        PIPELINE_NAME: 'otel-sidecar-cicd/deploy-to-staging'
        CF_API_KEY: ${{ secrets.CODEFRESH_API_TOKEN }}
        #MY_ENV_VAR: "FOOBAR"
        MY_ENV_VAR: {{ env.SHORT_GITHUB_SHA }}
      id: run-pipeline
      with:
        args: -v GITHUB_REF=${{ github.ref }} -v GITHUB_SHA=$GITHUB_SHA -v MY_ENV_VAR=${{ env.MY_ENV_VAR }}  -v SHORT_GITHUB_SHA=${{ env.SHORT_GITHUB_SHA }}