name: Deploy
on:
  push:
    tags:
      - 'd*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Codefresh pipeline runner
      uses: codefresh-io/codefresh-pipeline-runner@v7
      env:
        PIPELINE_NAME: 'otel-sidecar-cicd/deploy-to-staging'
        CF_API_KEY: ${{ secrets.CODEFRESH_API_TOKEN }}
        GITHUB_SHA: ${{ github.sha }}
      id: run-pipeline
      with:
        args: -v GITHUB_REF=${{ github.ref }} -v GITHUB_SHA=sha-${GITHUB_SHA::8}