name: Deploy
on:
  push:
    tags:
      - 'd*'

env:
  GITHUB_SHA: ${{ github.sha }}
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Set environment variables
      run: |
        echo "MY_ENV_VAR=sha-${GITHUB_SHA::8}" >> $GITHUB_ENV

    - name: Codefresh pipeline runner
      uses: codefresh-io/codefresh-pipeline-runner@v7
      env:
        PIPELINE_NAME: 'otel-sidecar-cicd/deploy-to-staging'
        CF_API_KEY: ${{ secrets.CODEFRESH_API_TOKEN }}
      id: run-pipeline
      with:
        args: -v GITHUB_REF=${{ github.ref }} -v MY_ENV_VAR=${{ env.MY_ENV_VAR }}
