name: Deploy
on:
  push:
    tags:
      - 'd*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: echo "Trigger on ALL branches"
    - name: Run a multi-line script
      run: |
        echo "Only on featuer branches1"
        echo "Only on featuer branches2"
