name: Deploy
on:
  push:
    tags:
      - 'd*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: echo "Trigger on TAGS with a prefix of d"
    - name: Run a multi-line script
      run: |
        echo "Only on tags with prefix of d"
        echo "Only on tags with prefix of d"
