name: Deploy
on:
  push:
    tags:
      - 'v*'
    branches:
      - main

env:
  GITHUB_SHA: ${{ github.sha }}
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Set image tag
      run: |

        if [[ $GITHUB_REF == refs/tags/* ]]; then
          echo IMAGE_TAG=${GITHUB_REF##*/} >> $GITHUB_ENV
        elif [[ $GITHUB_REF == refs/heads/* ]]; then
          echo "IMAGE_TAG=sha-${GITHUB_SHA::8}" >> $GITHUB_ENV
        fi 
  
    - name: Codefresh pipeline runner
      uses: codefresh-io/codefresh-pipeline-runner@v7
      env:
        PIPELINE_NAME: 'otel-sidecar-cicd/deploy-to-staging'
        CF_API_KEY: ${{ secrets.CODEFRESH_API_TOKEN }}
      id: run-pipeline
      with:
        args: -v IMAGE_TAG=${{ env.IMAGE_TAG }}
